#cloud-config

# run commands
# default: none
# runcmd contains a list of either lists or a string
# each item will be executed in order at rc.local like level with
# output to the console
# - runcmd only runs during the first boot
# - if the item is a list, the items will be properly executed as if
#   passed to execve(3) (with the first arg as the command).
# - if the item is a string, it will be simply written to the file and
#   will be interpreted by 'sh'
#
# Note, that the list has to be proper yaml, so you have to quote
# any characters yaml would eat (':' can be problematic)
runcmd:
 - echo "Started script at $(date)" > /Start.txt
 - apt add-apt-repository universe 
 - apt -f install zip unzip rdate python-pyftpdlib
 - git clone "https://github.com/microsoft/DefendTheFlag.git" /usr/bin/DefendTheFlag
 - unzip /usr/bin/DefendTheFlag/Downloads/Ubuntu-Katoolin/kali.zip -d /home/Cookies
 # add Kali repo to Ubuntu
 - echo "deb [trusted=yes] http://http.kali.org/kali kali-rolling main contrib non-free" >> /etc/apt/sources.list
 #- git clone "https://github.com/s-h-3-l-l/katoolin3"
 #- cd katoolin3/
 #- chmod +x ./install.sh
 #- sudo ./install.sh
 #- sudo katoolin3
 - sudo apt -y update && sudo apt -y upgrade
 - echo "Ended script at $(date)" > /End.txt
 - sudo reboot

bootcmd:
#  - echo "Started Boot script at $(date)" > /Boot.txt
#  - cd katoolin3/
#  - chmod +x ./update.sh
#  - sudo ./update.sh
 - sudo apt -y install python3-impacket hydra armitage
 - echo "Ended Boot script at $(date)" > /Boot.txt
